### ISSUE TITLE
Combined interfaces don't get generated

### ISSUE THREAD

**Issue by gergovari** [dart-lang/jnigen#392] opened 2023-09-13 11:26 UTC
```java
public interface SeekableInputOutputStream extends SeekableOutputStream, SeekableInputStream {
}
```

Creates an empty `.implement` method.

**Comment by HosseinYousefi** [comment] 2023-09-13 12:07
Duplicate of https://github.com/dart-lang/jnigen/issues/373.

**Closed by HosseinYousefi** 2023-09-13 12:07 UTC
Labels: closed-duplicate
