### ISSUE TITLE
Unable to generate files from jnigen

### ISSUE THREAD

**Issue by thisisamank** [dart-lang/jnigen#199] opened 2023-03-10 17:08 UTC
I am trying to setup `jnigen` and run the basic sample project.
edit: I have tried this on jdk 18,17 and 11.
On running  `dart run jnigen --config jnigen.yaml`
I am getting this
``` bash
(jnigen) INFO: Building ApiSummarizer component. This might take some time. 
The build will be cached for subsequent runs

(jnigen) INFO: execute mvn --batch-mode --update-snapshots -f /Users/thisisamank/.pub-cache/hosted/pub.dev/jnigen-0.3.0/java/pom.xml assembly:assembly
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for 'com.github.dart_lang.jnigen:ApiSummarizer:jar:0.0.1-SNAPSHOT'
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-assembly-plugin is missing. @ line 53, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/maven-metadata.xml
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/maven-metadata.xml (1.3 kB at 2.2 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.800 s
[INFO] Finished at: 2023-03-10T22:35:10+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.5.0 among available goals help, single -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch
[ERROR] Re-run Maven using the '-X' switch to enable verbose output
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException


maven exited with 1
Unhandled exception:
PathNotFoundException: Deletion failed, path = './.dart_tool/jnigen/target' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
<asynchronous suspension>
#2      buildApiSummarizer (package:jnigen/src/tools/build_summarizer.dart:52:5)
<asynchronous suspension>
#3      buildSummarizerIfNotExists (package:jnigen/src/tools/build_summarizer.dart:75:5)
<asynchronous suspension>
#4      generateJniBindings (package:jnigen/src/generate_bindings.dart:20:3)
<asynchronous suspension>
#5      main (file:///Users/thisisamank/.pub-cache/hosted/pub.dev/jnigen-0.3.0/bin/jnigen.dart:16:3)
<asynchronous suspension>
```

My `jnigen.yaml` file looks like this :
```yaml
android_sdk_config:
  add_gradle_deps: true

output:
  c:
    library_name: android_utils
    path: src/android_utils/
  dart:
    path: lib/android_utils.dart
    structure: single_file

source_path:
  - "android/app/src/main/java"
classes:
  - "com.example.jni_example.AndroidUtils"

```

can someone please help me with this?

**Comment by thisisamank** [comment] 2023-03-10 21:09
Update: It worked once I changed my maven version to `3.9.0` from `4.x-alpha`

**Comment by mahesh-hegde** [comment] 2023-03-21 14:09
I think we have to check if this works: https://github.com/islandoftex/arara/issues/113#issuecomment-413151150 .

In the meanwhile stick with 3.9.0

**Comment by thisisamank** [comment] 2023-03-21 21:18
Looks like the fix you linked should do the job too. Thanks!!

**Comment by mahesh-hegde** [comment] 2023-03-22 03:27
I think it will cumbersome for you to build the summarizer manually using maven command and place it in appropriate folder. That's why a setup script is supposed to do this.

**Comment by seifibrahim32** [comment] 2023-03-28 06:31
Hello , i think you should download the latest Maven , go to Kaven website and download the bin file from the website , after that copy it to Program Files and add the bin folder to PATH.
https://maven.apache.org/download.cgi
Download the bin.zip file

For instructions : 
https://maven.apache.org/install.html

To make sure it works perfect ,try to open cmd or Powershell , and type mvn --version.
If works , so be sure that the issue comes from Java , so you owe to delete it and install it again from Oracle , if you will use Java 19 , the distributionUrl for Android will accept Gradle from 7.6.
if less so check the Android documentation,
If any help : assist me on seifibrahim32@gmail.con.
I can make Google Meet also

If works , close the 
@thisisamank

**Comment by mahesh-hegde** [comment] 2023-03-31 13:07
I am marking this as `good first issue`.

If any potential contributor wants to solve this, 

1. You have to change the maven command here.
  https://github.com/dart-lang/jnigen/blob/070e529b237c63ce574b64535aaf44cdccb5d9c0/jnigen/lib/src/tools/build_summarizer.dart#L37

2. Preferably run the command manually in `jnigen/java` and resolve any errors / warnings related to POM.

3. Preferably attach a screenshot of this working on maven 4.x-alpha (Because we run stable on CI) and submit a PR.

If you run into any issues, feel free to ask here on this thread only.

**Comment by alex-james-dev** [comment] 2023-04-04 17:44
Hi,

I'd like to attempt to work on this issue, assuming nobody else is currently working on it?

**Comment by HosseinYousefi** [comment] 2023-04-04 18:39
> Hi,
> 
> I'd like to attempt to work on this issue, assuming nobody else is currently working on it?

I guess not. Go ahead!

**Comment by alex-james-dev** [comment] 2023-04-06 09:13
> > Hi,
> > I'd like to attempt to work on this issue, assuming nobody else is currently working on it?
> 
> I guess not. Go ahead!

Thanks, will do!

**Comment by alex-james-dev** [comment] 2023-04-24 13:50
Thank you @mahesh-hegde for your [instructions](https://github.com/dart-lang/jnigen/issues/199#issuecomment-1491901244) to solve this issue, they were very helpful :+1:. 

# Reproducing the issue
Maven 4.x fails when building ApiSummarizer.jar.

```Console
alexander:java$ mvn -v
Apache Maven 4.0.0-alpha-5 (26d10a4bf9a2df75feef60da01d8706f2bf77a47)
alexander:java$ mvn assembly:assembly
[INFO] -------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -------------------------------------------------------------------------------------------------
[ERROR] Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.5.0 among available goals help, single -> [Help 1]
```

However, Maven 3.x successfully builds ApiSummarizer.jar.

``` Console
alexander:java$ mvn -v
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
alexander:java$ mvn assembly:assembly
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

# Solution
As we can see in @mahesh-hegde's [comment](https://github.com/dart-lang/jnigen/issues/199#issuecomment-1477905763) the solution to this issue is to change the Maven command from `mvn assembly:assembly` to `mvn compile assembly:single`.

Manually running `mvn compile assembly:single` produces the following error:

```Console
alexander:java$ mvn -v
Apache Maven 4.0.0-alpha-5 (26d10a4bf9a2df75feef60da01d8706f2bf77a47)
alexander:java$ mvn compile assembly:single
[INFO] -------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.5.0:single (default-cli) on project ApiSummarizer: Error reading assemblies: No assembly descriptors found. -> [Help 1]
```

We can resolve this error by replacing `descriptorId` with `descriptorRef` in pom.xml. 
Having made this change `mvn compile assembly:single` builds successfully on Maven 4.x and 3.x.

```Console
alexander:java$ mvn -v
Apache Maven 4.0.0-alpha-5 (26d10a4bf9a2df75feef60da01d8706f2bf77a47)
alexander:java$ mvn compile assembly:single
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] -------------------------------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] -------------------------------------------------------------------------------------------------
```

```Console
alexander:java$ mvn -v
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
alexander:java$ mvn compile assembly:single
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

# Maven compile vs package
Although `mvn compile assembly:single` was suggested [here](https://github.com/islandoftex/arara/issues/113#issuecomment-413151150) to resolve the error. I think we might want to consider using a different build phrase. Currently, we are executing `mvn assembly:assembly` which runs the tests. However, `mvn compile assembly:single` doesn't run the tests. Therefore, if we want to run the tests I think we should use either `mvn test assembly:single` or `mvn package assembly:single`.
I'm currently using `mvn package assembly:single` because the Maven assembly[ plugin docs](https://maven.apache.org/plugins/maven-assembly-plugin/usage.html#gotcha) recommend the single goal to be bound to the package phase of the build.

# Testing
Here's the full output of `mvn package` on Maven 4.0.0-alpha-5:

```Console
alexander:java$ mvn -v
Apache Maven 4.0.0-alpha-5 (26d10a4bf9a2df75feef60da01d8706f2bf77a47)
Maven home: /opt/apache-maven-4.0.0-alpha-5
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-70-generic", arch: "amd64", family: "unix"
alexander:java$ mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.github.dart_lang.jnigen:ApiSummarizer >--------------------------
[INFO] Building ApiSummarizer 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] ---------------------------------------------[ jar ]---------------------------------------------
[WARNING] Version not locked for default bindings plugins [maven-resources-plugin, maven-jar-plugin], you should define versions in pluginManagement section of your pom.xml or parent
[INFO] 
[INFO] --- resources:3.3.0:resources (default-resources) @ ApiSummarizer ---
[INFO] skip non existing resourceDirectory /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/src/main/resources
[INFO] skip non existing resourceDirectory /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/src/main/resources-filtered
[INFO] 
[INFO] --- compiler:3.10.1:compile (default-compile) @ ApiSummarizer ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 37 source files to /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/classes
[INFO] 
[INFO] --- resources:3.3.0:testResources (default-testResources) @ ApiSummarizer ---
[INFO] Copying 2 resources
[INFO] skip non existing resourceDirectory /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/src/test/resources-filtered
[INFO] 
[INFO] --- compiler:3.10.1:testCompile (default-testCompile) @ ApiSummarizer ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/test-classes
[INFO] 
[INFO] --- surefire:3.0.0-M7:test (default-test) @ ApiSummarizer ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.github.dart_lang.jnigen.apisummarizer.JSONComparisonTest
Note: javadoc: Loading source file src/test/resources/com/example/Example.java...
Note: javadoc: Constructing Javadoc information...
[  1570 ms] Initializing doclet
[   656 ms] Writing JSON
[   214 ms] Finished
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.982 s - in com.github.dart_lang.jnigen.apisummarizer.JSONComparisonTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ ApiSummarizer ---
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] 
[INFO] --- assembly:3.5.0:single (make-assembly) @ ApiSummarizer ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[WARNING] Artifact: com.github.dart_lang.jnigen:ApiSummarizer:jar:0.0.1-SNAPSHOT references the same file as the assembly destination file. Moving it to a temporary location for inclusion.
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[WARNING] Configuration option 'appendAssemblyId' is set to false.
Instead of attaching the assembly file: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/archive-tmp/ApiSummarizer.jar
with assembly file: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] Copying com.github.dart_lang.jnigen:ApiSummarizer:pom:0.0.1-SNAPSHOT to project local repository
[INFO] Copying com.github.dart_lang.jnigen:ApiSummarizer:jar:0.0.1-SNAPSHOT to project local repository
[INFO] Copying com.github.dart_lang.jnigen:ApiSummarizer:pom:consumer:0.0.1-SNAPSHOT to project local repository
[INFO] -------------------------------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] -------------------------------------------------------------------------------------------------
[INFO] Total time:  17.539 s
[INFO] Finished at: 2023-04-24T13:14:14+01:00
[INFO] -------------------------------------------------------------------------------------------------
```

Here's the full output of `mvn package` on Maven 3.9.1:

``` Console
alexander:java$ mvn -v
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /opt/apache-maven-3.9.1
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-70-generic", arch: "amd64", family: "unix"
alexander:java$ mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.github.dart_lang.jnigen:ApiSummarizer >--------------
[INFO] Building ApiSummarizer 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.0:resources (default-resources) @ ApiSummarizer ---
[INFO] skip non existing resourceDirectory /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/src/main/resources
[INFO] 
[INFO] --- compiler:3.10.1:compile (default-compile) @ ApiSummarizer ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 37 source files to /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/classes
[INFO] 
[INFO] --- resources:3.3.0:testResources (default-testResources) @ ApiSummarizer ---
[INFO] Copying 2 resources
[INFO] 
[INFO] --- compiler:3.10.1:testCompile (default-testCompile) @ ApiSummarizer ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/test-classes
[INFO] 
[INFO] --- surefire:3.0.0-M7:test (default-test) @ ApiSummarizer ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.github.dart_lang.jnigen.apisummarizer.JSONComparisonTest
Note: javadoc: Loading source file src/test/resources/com/example/Example.java...
Note: javadoc: Constructing Javadoc information...
[  1481 ms] Initializing doclet
[   556 ms] Writing JSON
[   249 ms] Finished
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.838 s - in com.github.dart_lang.jnigen.apisummarizer.JSONComparisonTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ ApiSummarizer ---
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] 
[INFO] --- assembly:3.5.0:single (make-assembly) @ ApiSummarizer ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[WARNING] Artifact: com.github.dart_lang.jnigen:ApiSummarizer:jar:0.0.1-SNAPSHOT references the same file as the assembly destination file. Moving it to a temporary location for inclusion.
[INFO] Building jar: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[WARNING] Configuration option 'appendAssemblyId' is set to false.
Instead of attaching the assembly file: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/archive-tmp/ApiSummarizer.jar
with assembly file: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/target/ApiSummarizer.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.195 s
[INFO] Finished at: 2023-04-24T13:20:00+01:00
[INFO] ------------------------------------------------------------------------
```

I also tested the changes by running [HosseinYousefi/jnigen_example](https://github.com/HosseinYousefi/jnigen_example) where jnigen dependency has been set to the local modified version of jnigen:

``` yaml

  jnigen:
    path: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen
 jni:
    path: /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jni
```
Running  [HosseinYousefi/jnigen_example](https://github.com/HosseinYousefi/jnigen_example) on Maven 4.0.0-alpha-5:
``` Console
alexander:jnigen_example$ mvn -v
Apache Maven 4.0.0-alpha-5 (26d10a4bf9a2df75feef60da01d8706f2bf77a47)
Maven home: /opt/apache-maven-4.0.0-alpha-5
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-70-generic", arch: "amd64", family: "unix"
alexander:jnigen_example$ dart run jnigen --config jnigen.yaml
Building package executable... (6.2s)
Built jnigen:jnigen.
(jnigen) INFO: Building ApiSummarizer component. This might take some time. The build will be cached for subsequent runs.
(jnigen) INFO: execute mvn package --batch-mode --update-snapshots -f /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jnigen/java/pom.xml
(jnigen) INFO: execute java -jar .dart_tool/jnigen/ApiSummarizer.jar -s java dev.dart.Example
(jnigen) INFO: Using c root = src/example/
(jnigen) INFO: Creating dart init file ...
(jnigen) INFO: writing c bindings to File: 'src/example/example.c'
(jnigen) INFO: Copying auxiliary files...
(jnigen) INFO: Running clang-format on C bindings
(jnigen) INFO: Generating C + Dart Bindings
(jnigen) INFO: Running dart format...
(jnigen) INFO: Completed
alexander:jnigen_example$ dart run jni:setup -p jni -s src/example
Building package executable... (6.8s)
Built jni:setup.
selecting source directories: [src/example, /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jni/src]
+ [.dart_tool/jni/jni_native_build_WNLAIY] cmake /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen_example/src/example
+ [.dart_tool/jni/jni_native_build_WNLAIY] cmake --build .
+ [.dart_tool/jni/jni_native_build_EOAUXH] cmake /home/alexander/Documents/Software/GSoC 2023/Maven Bug/jnigen/jni/src
+ [.dart_tool/jni/jni_native_build_EOAUXH] cmake --build .
alexander:jnigen_example$ javac java/dev/dart/Example.java
alexander:jnigen_example$ dart run jnigen_example:sum 17 25
Building package executable... (4.3s)
Built jnigen_example:sum.
42
```

**Closed** 2023-04-27 10:49 UTC
Labels: good first issue
